### ISSUE TITLE
Any more updates to code / documentation?

### ISSUE THREAD

**Issue by rajeshvaya** [abugnais/restful-shopping-cart#1]
We will be completing the review of the code by end of day ?

**Comment by rajeshvaya** [comment]
Adding @CaptainYouz @wowi42

**Comment by abugnais** [comment]
still working on it!

**Comment by abugnais** [comment]
right now im migrating tests to sinon + unexpected to enhance the code coverage and using bluebird to promisify mongoose methods but I dont have alot of time to do that during work days
